# permissions for end users to view podrestarts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: podrestart-operator
    app.kubernetes.io/managed-by: kustomize
  name: podrestart-viewer-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - podrestarts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.example.com
  resources:
  - podrestarts/status
  verbs:
  - get
