---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - example.example.com
  resources:
  - podrestarts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.example.com
  resources:
  - podrestarts/finalizers
  verbs:
  - update
- apiGroups:
  - example.example.com
  resources:
  - podrestarts/status
  verbs:
  - get
  - patch
  - update
